# Generated by Django 2.0.1 on 2019-07-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Coffee_Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Coffee_Pod',
            },
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Flavour',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Machine',
            },
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'PackSize',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.CreateModel(
            name='WL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'WL',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='Type',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Type'),
        ),
        migrations.AddField(
            model_name='category',
            name='coffeePod',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Coffee_Pod'),
        ),
        migrations.AddField(
            model_name='category',
            name='flavour',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Flavour'),
        ),
        migrations.AddField(
            model_name='category',
            name='machine',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Machine'),
        ),
        migrations.AddField(
            model_name='category',
            name='packsize',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.PackSize'),
        ),
        migrations.AddField(
            model_name='category',
            name='wl',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.WL'),
        ),
    ]
